name: up_game_back
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  netframework:
    git: https://github.com/Up-game/NetFramework.git

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
